### ISSUE TITLE
添加socks自定义服务器

### ISSUE THREAD

**Issue by RaukaRur** [getsurfboard/surfboard#103]
有考虑添加一个自定义服务器吗 用于局域网共享

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/general/socks5_listen

你也可以在设置里面直接设置

**Comment by RaukaRur** [comment]
我的意思是 使用手机 访问电脑 V2rayn 打开的socks代理

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/proxy/external-proxy/socks5
