### ISSUE TITLE
Problems about Host and DNS

### ISSUE THREAD

**Issue by sakaman** [getsurfboard/surfboard#105]
Hi, I found two problems.
## Problem
1. It does not work to define server host
I just set two hosts in [Host],
```conf
[Host]
# myserver.com is proxy host
myserver.com = 1.2.3.4
abc.com = 5.6.7.8
```
and ping & nslookup them in termux, but myserver.com reported another ip address though abc.com reported 5.6.7.8.

2. DNS not work
```conf
[General]
dns-server: 1.1.1.1
```
Surfboard reported another DNS address.

Is there any way that I can solve them?

**Comment by getsurfboard** [comment]
The second question is a syntax problem, please check https://getsurfboard.com/docs/profile-format/general/dns_server

**Comment by sakaman** [comment]
> The second question is a syntax problem, please check https://getsurfboard.com/docs/profile-format/general/dns_server

It appears that the surfboard is reporting a different DNS server than 1.1.1.1, despite being in the same ASN. However, this is not necessarily a problem. When using the nslookup command in Termux, it shows that the DNS server being used is 8.8.8.8.

**Comment by getsurfboard** [comment]
If you use 'nslookup' without open surfboard, will it use the dns server assigned by DHCP? 

I remember 'dig' using hardcoded dns server, which is 8.8.8.8, but I am not sure whether 'nslookup' is using hardcoded dns server.

**Comment by sakaman** [comment]
> If you use 'nslookup' without open surfboard, will it use the dns server assigned by DHCP?
> 
> I remember 'dig' using hardcoded dns server, which is 8.8.8.8, but I am not sure whether 'nslookup' is using hardcoded dns server.

I have gotten it that termux uses its default hardcoded DNS server, which is specified in the `$PREFIX/etc/resolv.conf` file. When using Surfboard, Google Chrome reports the same DNS server as specified in the `chrome://net-export` page.
