### ISSUE TITLE
改进建议：希望线路列表出一个紧凑模式

### ISSUE THREAD

**Issue by veizei-K** [getsurfboard/surfboard#106]
线路名称和测速结果占一行，然后适当缩小字号 使一屏内显示尽可能多的线路数目，这样便于快速筛选合适线路，在线路特别多的情况下。而且也不用显示协议类型，因为我们普通人只关心能不能用。
![IMG_20230527_010855](https://github.com/getsurfboard/surfboard/assets/129288685/5f48c21a-7e72-4c82-aa0f-2b3bf02929ed)

还有一个就是：希望软件关闭后再打开能保留上次测试延时的结果。

**Comment by iambonboncat** [comment]
点一下右上角的方块
