### ISSUE TITLE
[Bug] skip-proxy未生效

### ISSUE THREAD

**Issue by cubarco** [getsurfboard/surfboard#114]
### 简述：
我希望在手机上使用**代理**访问家庭网络中的192.168.1.1机器。
我的做法是，配置skip-proxy，移除其中的192.168.0.0/16项，然后在Rule中添加192.168.1.0/24走代理的规则。但是这么做之后，用浏览器无法访问192.168.1.1，而且surfboard日志中没有192.168.1.1的访问记录。

### 配置：
```
[General]
...
skip-proxy = 127.0.0.1
...

[Rule]
IP-CIDR,192.168.1.0/24,Proxy
```

### 预期结果：
使用浏览器访问192.168.1.1，返回网页

### 实际结果：
使用浏览器访问192.168.1.1，报错ERR_CONNECTION_TIMED_OUT

### 调试尝试：
使用上述配置后，尝试在手机中执行`ip r show table all`，看到如下路由表：
```plain
...
default dev tun0 table tun0 proto static scope link
throw 10.0.0.0/8 table tun0 proto static scope link
throw 100.64.0.0/10 table tun0 proto static scope link
throw 169.254.0.0/16 table tun0 proto static scope link
throw 172.16.0.0/12 table tun0 proto static scope link
throw 192.0.0.0/24 table tun0 proto static scope link
throw 192.88.99.0/24 table tun0 proto static scope link
throw 192.168.0.0/16 table tun0 proto static scope link
...
```
猜测是surfboard未使用skip-proxy中的定义内容设置路由表，而是硬编码了相应网段。`throw 192.168.0.0/16 table tun0 proto static scope link`这条路由让192.168.1.1的请求绕过了surfboard.
所以我的猜测是skip-proxy配置并未完全实现？

**Comment by getsurfboard** [comment]
设置 - VPN - 打开“局域网流量过滤”

**Comment by cubarco** [comment]
> 设置 - VPN - 打开“局域网流量过滤”

谢谢，已解决～
