### ISSUE TITLE
当订阅链接api参数有多个时, 只会留下第一个导致无法更新订阅

### ISSUE THREAD

**Issue by Special-Week** [getsurfboard/surfboard#120]
比如机场给我的订阅链接是 "https://abc.api/api/v1/client/subscribe?token=abcdefg&security=1234567"
第一次导入的时候可以成功导入, 但是导入后查看会发现订阅链接&符号后面的参数不见了, 只剩下一个token参数. 
点击"分享---复制订阅链接"导出来链接也是只剩下"https://abc.api/api/v1/client/subscribe?token=abcdefg"
也导致了更新订阅访问api时缺少第二个参数无法访问到订阅信息

**Comment by getsurfboard** [comment]
配置内容格式问题，请按照标准适配

https://getsurfboard.com/docs/profile-format/managed_config
