### ISSUE TITLE
建议 --快捷设置图标

### ISSUE THREAD

**Issue by nimenhagg** [getsurfboard/surfboard#121]
Surfboard 的快捷设置小图标点击后会收起快捷设置，不太舒服，有时候设置完 Surfboard 的状态还想设置别的，这时候要重新开快速设置
Clash 的图标和手电筒之类的开关一样，不会收起快捷设置

**Comment by getsurfboard** [comment]
设置，通知，关闭 自动折叠通知栏

nimenhagg ***@***.***> 于 2023年7月23日周日 14:18写道：

**Comment by nimenhagg** [comment]
我是傻逼

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nimenhagg** [comment]
problem solved
