### ISSUE TITLE
Request to support the vless protocol. Now some masters have written the vless protocol section into the cloudflare worker that can be used for free. Therefore, the usage base of this protocol is already very large. Please add support for this protocol

### ISSUE THREAD

**Issue by FredToyert** [getsurfboard/surfboard#122]
Request to support the vless protocol. Now some masters have written the vless protocol section into the cloudflare worker that can be used for free. Therefore, the usage base of this protocol is already very large. Please add support for this protocol

**Comment by getsurfboard** [comment]
No plan for that, please use v2ray instead.
