### ISSUE TITLE
Quick tile doesn't work 

### ISSUE THREAD

**Issue by HotarunIchijou** [getsurfboard/surfboard#126]
I set up a shadowsocks profile in the app, but when I press on the Quick Tile, it does nothing and sometimes I get a message which says that surfboard keeps stopping

**Comment by getsurfboard** [comment]
If you run surfboard in Android 14, it has a bug related to Android 14, which will be fixed in next release.

**Comment by HotarunIchijou** [comment]
The bug has been fixed in the new version
