### ISSUE TITLE
ipv6显示不正确

### ISSUE THREAD

**Issue by MagnetOscar** [getsurfboard/surfboard#127]
![Screenshot_2023-08-18-18-37-42-586_com getsurfboard-edit](https://github.com/getsurfboard/surfboard/assets/63010594/12126da4-18ad-480b-afcd-e3ec2ed0008e)
最近不管是wifi还是流量都显示ipv6了，google play版本一直没啥更新，这里显示应该是宽度不够所以下半部分显示不完全，建议修一下UI

**Comment by getsurfboard** [comment]
Fixed in 2.21.5
