### ISSUE TITLE
Some subscriptions are not starting

### ISSUE THREAD

**Issue by amirparto1** [getsurfboard/surfboard#128]
When I use some subscription links, the app stucks in "starting..." button and after 5 seconds it stops. These links are working fine on other apps. Here some of the links example:

https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity

https://proxy.yugogo.xyz/trojan/sub

https://proxy.yiun.xyz/trojan/sub

https://api.sublink.dev/sub?target=surfboard&url=https%3A%2F%2Ffreenodeworker.amirparto.workers.dev%2Fsub%2FIRC&insert=false&config=https%3A%2F%2Fsubweb.s3.fr-par.scw.cloud%2FRemoteConfig%2Funiversal%2Furltest.ini&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false

**Comment by getsurfboard** [comment]
Fix will be released in next version, thx for the feedback.
