### ISSUE TITLE
更新App提示方式的一些建议

### ISSUE THREAD

**Issue by Yerosius** [getsurfboard/surfboard#130]
目前有新版本更新仅在设置-其他内有提示更新，有新版本更新无法被及时注意到，希望能在Dashboard和Seetings页面右上角三个点左面加上有新版本可用的图标

**Comment by getsurfboard** [comment]
目前关于内的版本更新提示是引导到github release的，发布的是测试性质的包体，不太适合面向所有用户提示推送

Yerosius ***@***.***> 于 2023年8月30日周三 14:05写道：
