### ISSUE TITLE
Permanent background color

### ISSUE THREAD

**Issue by HotarunIchijou** [getsurfboard/surfboard#133]
It seems that background color doesn't changes depending on the color scheme (screen record attached). In dark theme it's #1C1B1F which is same as "on surface" and "on background" in the baseline (default) color scheme. I think it's a bug and the background color should changes depend on system scheme or selected scheme and its token should be Surface (md.sys.color.surface in case of system color scheme)

https://github.com/getsurfboard/surfboard/assets/113282550/58f2fd09-eb87-4fc6-ad4d-7390239c0f9d

**Comment by getsurfboard** [comment]
Thx for the feedback, color issue will be fixed in next release.
