### ISSUE TITLE
Windows版surfboard?

### ISSUE THREAD

**Issue by Yerosius** [getsurfboard/surfboard#134]
如题，目前在windows端还没有兼容surge配置的软件，请问未来可以考虑开发windows版本surfboard吗？

**Comment by getsurfboard** [comment]
我本身不是windows用户，所以暂时没有windows端的开发计划，类似的windows端软件可以尝试下 [Maple](https://github.com/YtFlow/Maple)

**Comment by unknown989** [comment]
我尝试了 Maple，但配置不匹配，你能写一个关于如何设置它的指南吗？
