### ISSUE TITLE
希望增加的功能

### ISSUE THREAD

**Issue by OSNewbie** [getsurfboard/surfboard#136]
由于机场的订阅节点，被墙几率很高，因为他用了自动换IP功能，希望你也可以用什么办法，弄一个功能自动检测节点是否能使用，每次要测速测试节点节点才知道是否能正常使用？就比较麻烦 ，希望对新的协议给予支持，主要是你支持的代理协议的协议，要么就是稳定性存在问题，要么就是被墙的几率很高

**Comment by OSNewbie** [comment]
支持新的协议是好的，防火墙在升级，你代理软件也得升级啊

**Comment by getsurfboard** [comment]
Currently no plan for that.
