### ISSUE TITLE
请问是否支持Surge的[Proxy]的underlying-proxy和[Proxy Group]的include-other-group字段功能

### ISSUE THREAD

**Issue by TingTing1990** [getsurfboard/surfboard#139]
RT

**Comment by getsurfboard** [comment]
- [ ] underlying-proxy
- [X] include-other-group

**Comment by getsurfboard** [comment]
`include-other-group` support will be released in next version.

Currently there is no plan to support the `underlying-proxy` param.

**Comment by uclort** [comment]
请问大概多久发布下一个版本？
`include-other-group` 期待支持。

**Comment by getsurfboard** [comment]
> 请问大概多久发布下一个版本？ `include-other-group` 期待支持。

https://github.com/getsurfboard/surfboard/releases/tag/2.22.0
