### ISSUE TITLE
请求允许订阅导入时忽略wireguard和ponte节点的错误信息

### ISSUE THREAD

**Issue by atsrxL** [getsurfboard/surfboard#140]
请求在允许订阅导入时忽略wireguard和ponte节点的错误信息，以此达到和surge mac/ios配置的一致性

**Comment by getsurfboard** [comment]
Can you provide a sample profile for issue reproduction?

**Comment by atsrxL** [comment]
Sure.

For Ponte ,should  like this:
[General]
xxxxxxxx
[Proxy]
xxxxxxxx//* Ponte node no need to be specified in Proxy *//
[Proxy Group]
Proxy = DIRECT, DEVICE:PONTEMAC
Final, DIRECT
*********
For Wireguard:
[General]
xxxxxxxx
[Proxy]
xxxxxxxx
WG = wireguard, section-name=WireG, ip-version=v4-only
[Proxy Group]
Proxy = DIRECT, WG 
xxxxxxxx
Final, DIRECT

[WireGuard WireG]
private-key = ALn4363Lh1ecN6F/5ZxHJ7Ed1y5aZ2dpjf84RA&MRG8=
self-ip = 10.20.30.4
dns-server = 10.20.30.2
mtu = 1420
peer = (public-key = dStsVbIaM60OEHaVytO0Krb14cQnKiEu2XXxizJFXkw=, allowed-ips = 0.0.0.0/0, keepalive = 15, endpoint = abcd.cc:12222)


REF:
https://kb.nssurge.com/surge-knowledge-base/v/zh/guidelines/ponte
https://manual.nssurge.com/policy/wireguard.html

FYI

**Comment by getsurfboard** [comment]
https://github.com/getsurfboard/surfboard/releases/tag/2.22.0
