### ISSUE TITLE
不支持 policy-regex-filter 吗？

### ISSUE THREAD

**Issue by uclort** [getsurfboard/surfboard#145]

**Comment by ninemonths** [comment]
支持，直接在策略组后面添加即可r

**Comment by uclort** [comment]
policy-regex-filter=日本，这样写过滤不出来

**Comment by uclort** [comment]
Auto-日本 = url-test, include-other-group=Node, policy-regex-filter=日本, tolerance=30, hidden=true

**Comment by getsurfboard** [comment]
> Auto-日本 = url-test, include-other-group=Node, policy-regex-filter=日本, tolerance=30, hidden=true

正则是完整匹配的，可以试试

`.*日本.*`

**Comment by uclort** [comment]
> > Auto-日本 = url-test, include-other-group=Node, policy-regex-filter=日本, tolerance=30, hidden=true
> 
> 正则是完整匹配的，可以试试
> 
> `.*日本.*`

谢谢，问题已解决。

**Comment by athlonreg** [comment]
> > Auto-日本 = url-test, include-other-group=Node, policy-regex-filter=日本, tolerance=30, hidden=true
> 
> 正则是完整匹配的，可以试试
> 
> `.*日本.*`

可以改成关键字匹配吗，完整匹配会出现和 surge 配置文件不通用的情况，按国家分组容易出现匹配不到节点的问题，如果用关键字匹配的话正则写法也会更简单一些

**Comment by getsurfboard** [comment]
好的，下个版本修改成部分匹配

**Comment by athlonreg** [comment]
> 好的，下个版本修改成部分匹配

非常感谢
