### ISSUE TITLE
Wireguard issue

### ISSUE THREAD

**Issue by atsrxL** [getsurfboard/surfboard#146]
With same config between ios & surfboard , the ios one can access remote Lan devices, but surfboard cannot 
If set the wireguard as global proxy, on surfboard dashboard I can see the change of public IP as server one, but still can't get Lan access, Please help.
Coud provide my personal WG config if needed.
TY

**Comment by getsurfboard** [comment]
If you want to use surfboard to redirect network traffic towards LAN, remember to turn on "LAN traffic filter" on VPN section of app settings.

Surfboard won't handle LAN traffic by default to improve performance and avoid error caused by incomplete profile rules.

**Comment by atsrxL** [comment]
Okay found the settings, apologize for my mistake, TY for help.

getsurfboard ***@***.***>于2023年10月10日 周二00:50写道：
