### ISSUE TITLE
Is it possible to add an item for hosts?

### ISSUE THREAD

**Issue by yonsanjohnson** [getsurfboard/surfboard#150]
I am new here, I have no idea on how to add extra hosts but not in the profile. I am afraid of losing hosts after updating the profile.
is there any item for adding hosts but not affect the profile? thank you so much.

E,g. Like CLASH you can add hosts in a place which wont affect profiles.

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/host/
