### ISSUE TITLE
希望支持Vless和HY2协议

### ISSUE THREAD

**Issue by Yerosius** [getsurfboard/surfboard#154]
如题，V2Board目前原生支持了HY2协议，目前HY2的节点也越来越多了，希望Surfboard能跟进，并一并将Vless也支持下

**Comment by owo10086** [comment]
怎么不用clash meta

**Comment by Yerosius** [comment]
> 怎么不用clash meta

Clash内核删库了，之前一直存在难以解决的路径穿越漏洞，无人维护之后安全系数更是未知数

**Comment by 23101X** [comment]
对的，有计划支持hy2吗，大佬
