### ISSUE TITLE
socks5携带scv参数时不可用

### ISSUE THREAD

**Issue by YipSzeho** [getsurfboard/surfboard#155]
由于需要使用subconverter转换订阅，会携带skip-cert-verify参数，但该参数无论真假都会导致socks5节点不可用。可否自动忽略节点协议不支持的参数

**Comment by getsurfboard** [comment]
可以提供一个sample吗，把服务器域名端口用户名密码什么的模糊掉

**Comment by YipSzeho** [comment]
```
[Proxy]
DIRECT = direct
🇯🇵 日本01 ORACLE = socks5, domain.com, port, skip-cert-verify=true, tfo=false, udp-relay=true
```

**Comment by getsurfboard** [comment]
如果是这种写法，按道理 skip-cert-verify 参数会被忽略，你确定其他的东西不动，只是把 skip-cert-verify改成false就可以通了吗？

**Comment by YipSzeho** [comment]
再排列组合测试了下，发现是只能携带一个参数，多于一个参数就不可用了
![IMG_20231105_000937](https://github.com/getsurfboard/surfboard/assets/58989046/3f198890-e700-427b-be0e-306706f0e315)

**Comment by getsurfboard** [comment]
明白了，你的参数是被当成用户名密码了，我后面版本处理一下

**Comment by getsurfboard** [comment]
修复会在下个版本外放
