### ISSUE TITLE
ColorOS下拉磁贴的瞬间是灰的

### ISSUE THREAD

**Issue by naniccc** [getsurfboard/surfboard#159]
https://github.com/getsurfboard/surfboard/assets/57870281/9c3a5637-6966-449c-bd8e-3016091e5a4a

ColorOS下拉磁贴的瞬间是灰的

**Comment by Lmtmine** [comment]
我也有这个问题，color的安卓14版本，我的一直是灰的，点击压根没用，必须点进程序里面开关

**Comment by Jiahua0** [comment]
我的也是

**Comment by Un1Gfn** [comment]
One UI 5.1 / surfboard 2.22.2  
也有下拉瞬間灰色問題
