### ISSUE TITLE
功能建议：新增一个全局Socks5端口代理

### ISSUE THREAD

**Issue by r8t0** [getsurfboard/surfboard#16]
场景：手机需要规则代理，局域网内其他设备需要全局但只能设置socks5代理不能装软件
现在可以在局域网内启用http、socks5代理，希望可以再额外监听一个socks5端口，通过这个端口的流量直接全部走代理，无视出站规则设置。

**Comment by getsurfboard** [comment]
需求过于小众，后续会考虑使用来源IP规则实现指定全部走加速

https://manual.nssurge.com/rule/misc-rule.html

**Comment by r8t0** [comment]
多谢，这样也能解决这个问题
