### ISSUE TITLE
打开surf board以后收不到微信通知

### ISSUE THREAD

**Issue by Lmtmine** [getsurfboard/surfboard#162]
问一下各位，我安卓手机用surfboard ，发现开着的期间，我的微信要么不通知要么打开微信没消息，过一段时间才突然出现（比如一个人在十二点给我发的消息，但是我在与他的聊天界面中一直没有，直到十二点半才会出现，显示发消息的时间还是十二点）这个是怎么回事啊？

**Comment by Yerosius** [comment]
经典小白发言，出问题就赖代理工具

**Comment by Lmtmine** [comment]
> 经典小白发言，出问题就赖代理工具

我要是懂我还会问吗？而且我只是把我的情况描述一遍而已，我要是确定是哪的问题，我还闲着无聊再问这个问题？

**Comment by Yerosius** [comment]
乐，经典小白，只会情绪化无脑喷



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月13日 10:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [getsurfboard/surfboard] 打开surf board以后收不到微信通知 (Issue #162) |

经典小白发言，出问题就赖代理工具

我要是懂我还会问吗？而且我只是把我的情况描述一遍而已，我要是确定是哪的问题，我还闲着无聊再问这个问题？

**Comment by Yerosius** [comment]
这么没素质的小白用一键连VPN得了，在这刷存在感？
挨抓跟我们有什么关系？


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月13日 10:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [getsurfboard/surfboard] 打开surf board以后收不到微信通知 (Issue #162) |

经典小白发言，出问题就赖代理工具

我要是懂我还会问吗？而且我只是把我的情况描述一遍而已，我要是确定是哪的问题，我还闲着无聊再问这个问题？

**Comment by Yerosius** [comment]
### 自己不懂还有理了是吧？本应该不懂？不懂还很自豪？翻墙圈就是因为你们这种sb小白搞臭的，自己还不知道？

**Comment by Lmtmine** [comment]
> ### 自己不懂还有理了是吧？本应该不懂？不懂还很自豪？翻墙圈就是因为你们这种sb小白搞臭的，自己还不知道？

说的太有道理了，只有您这种很厉害的人才配用，不懂就没资格用。我不懂我真该死，不应该问的，我就应该别活了。🤗🤗🤗

**Comment by GundamDr1ver** [comment]
你需要自己排查，至少简述一下排查的过程，帮别人省时间就是帮自己省时间，你自己真的看完了手册？真的排查了所有问题？或者干脆更换代理软件？大伙不是客服，那人是挺傻逼的，但是你抱着这么极端的心态根本没有意义，也学不到东西，如果你认为这是一个bug，而不是你的问题，就按照开发者的要求提供文字和文件，否则是在污染issues

**Comment by Lmtmine** [comment]
> 你需要自己排查，至少简述一下排查的过程，帮别人省时间就是帮自己省时间，你自己真的看完了手册？真的排查了所有问题？或者干脆更换代理软件？大伙不是客服，那人是挺傻逼的，但是你抱着这么极端的心态根本没有意义，也学不到东西，如果你认为这是一个bug，而不是你的问题，就按照开发者的要求提供文字和文件，否则是在污染issues

抱歉，我的表述不当。经过我自己最近的使用过程发现，这个问题只存在于第一天，不知道是为什么（仅个人使用情况来说）。我用clash和surfboard做了测试，发现是仅有surfboard代理的时候收不到消息（不是说软件有问题，我只是客观阐述自己的测试结果）。再之后我就我用了白名单模式，就发现没有这个问题，但是在用规则模式的时候，有出现过两次。随后我便长期开着代理，用规则模式，但是除了第一天的时候，这个问题并不严重。仅是会延迟几分钟，但是没有第一天严重。
我不敢说我排查了全部问题，但就目前我能想到的，已经全部测试过一遍了。我个人目前是认为可能是分流规则存在问题，我稍后会向开发者提供文字和文件。还有什么不妥的地方还希望各位能指出（如果各位愿意的话）。
另外我和他的争执给您带来不好的感受，我向您说声对不起。
