### ISSUE TITLE
从前天开始，就出现一直连不上的情况

### ISSUE THREAD

**Issue by huajiworld** [getsurfboard/surfboard#17]
节点没有任何问题，同样的节点在其他软件里能正常使用。测速的时候无论任何节点，延迟均为200ms左右，连接时只有DNS发生变化，IP地址不变 @getsurfboard [这是log](https://t.wss.ink/f/917xwlwzd8r)

**Comment by getsurfboard** [comment]
日志并未包含特别有用的信息，建议重现问题后马上导出日志

**Comment by huajiworld** [comment]
[log@getsurfboard ](https://t.wss.ink/f/91ji74c1cr0)

**Comment by huajiworld** [comment]
重启手机后就解决了，抱歉，麻烦你了
