### ISSUE TITLE
Socks5 Proxy setup guide. 

### ISSUE THREAD

**Issue by TheDeadGhost** [getsurfboard/surfboard#170]
I tried to add socks5 proxy on this app but after inputting the details by the manual of the web(ProxySOCKS5 = socks5, 1.2.3.4, 443, username, password, udp-relay=false)
but it says 0 dns, 0 hosts, 0 proxies 0 rules. Am I doing it wrong? or can you please give a detailed instruction of how to connect socks5 through this app?

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/proxy/external-proxy/socks5

https://getsurfboard.com/docs/profile-format/overview
