### ISSUE TITLE
include-other-group 是否不支持 通过policy-path获取节点的策略组

### ISSUE THREAD

**Issue by zuluion** [getsurfboard/surfboard#171]
```
[Proxy Group]
AIRPORT = select, policy-path=https://yournodes.com/nodes.txt
🇭🇰 AIRPORT-HK = select, include-other-group = "AIRPORT", policy-regex-filter=港|HK|HongKong
```

上述配置在 v2.22.0 中报错 `Proxy Group 🇭🇰 AIRPORT-HK has no proxies inside` 

改成 `🇭🇰 AIRPORT-HK = select, policy-path=https://yournodes.com/nodes.txt, policy-regex-filter=港|HK|HongKong` 可正常导入

**Comment by getsurfboard** [comment]
会在下个版本修复

**Comment by getsurfboard** [comment]
原因是include-other-group和include-all-proxies暂时不支持部分匹配，可以先用完全匹配兼容，后续会改成都支持部分匹配的
