### ISSUE TITLE
能否增加hosts填写选项呢？【已更新建议添加详细内容及图片文件】

### ISSUE THREAD

**Issue by yonsanjohnson** [getsurfboard/surfboard#173]
国产手机现在有fcm推送问题，导致使用一些国外软件如：whatsapp，Instagram等推送造成了很大的延迟和困扰。
使用surfboard的时候发现只要锁屏情况之下，以上聊天软件就不会再推送信息，除非点进APP之后消息才会弹出来。
但是：shadowsrock，SSR等软件不会出现这个情况~
通过测试之前的clash for Android 通过 在软件中添加hosts，把google的一些信息添加进去之后成功实现消息及时推送
除非是网络实在不太好的情况，轻微延迟。但绝对不会像之前那样只能通过点开APP才有信息。
请问Surfboard是否能否增加额外的hosts添加选项，就像CLASH那样是独立填写的，而不是写在配置文件或规则里。
谢谢~~

**Comment by getsurfboard** [comment]
具体是什么host配置呢？

**Comment by yonsanjohnson** [comment]
> 具体是什么host配置呢？

您好，主要希望能够做到有类似于Clash这样单独添加hosts的界面，而不影响订阅配置文件更新。
避免每次刷新订阅配置文件时又要打开手动再次添加，好像已添加的配置文件无法修改，只能更新的样子。
请看附图的方式~
而添加的hosts内容主要是，谷歌类的一些内容，这样就会使FCM顺利链接。
在国产机的国内定制系统，如：MIUI, 三星国行系统 我尝试过使用神机规则的“谷歌FCM”也无效。
而国外机或系统如：pixel8pro，三星台版系统，必须手动加hosts才可做到消息秒推或者延迟稍微几秒推送，
而不可能发生点进APP才可以看到消息。
看来只能通过手动添加hosts的方式才有效~《在CLASH上面是这样的》
还麻烦制作者您考虑这个功能，谢谢：
[mtalk.google.com](http://mtalk.google.com/) 108.177.97.188
[alt1-mtalk.google.com](http://alt1-mtalk.google.com/) 142.250.141.188
[alt2-mtalk.google.com](http://alt2-mtalk.google.com/) 142.250.115.188
[alt3-mtalk.google.com](http://alt3-mtalk.google.com/) 64.233.171.188
[alt4-mtalk.google.com](http://alt4-mtalk.google.com/) 142.250.152.188
....
[alt8-mtalk.google.com](http://alt8-mtalk.google.com/) 142.250.112.188
![未标题-1](https://github.com/getsurfboard/surfboard/assets/138011317/bff1e45c-00ff-4875-8df6-20ed1f304186)

**Comment by kljjh** [comment]
同需。现有的subconverter不支持hosts，所以实现hosts功能似乎只能靠覆写配置文件，即覆写配置模板中的[hosts]部分。希望添加相应功能。
![S31220-23473203_com android chrome](https://github.com/getsurfboard/surfboard/assets/29812342/ec934437-5062-4b8f-8ac7-9e1fd9192f54)

**Comment by yonsanjohnson** [comment]
请问这个问题是否能考虑加入软件呢？已经反馈那么长时间了，却没有任何回应。

**Comment by getsurfboard** [comment]
https://github.com/getsurfboard/surfboard/releases/tag/2.23.3

**Comment by 903247446** [comment]
我觉得是

**Comment by sieyr** [comment]
> 国产手机现在有fcm推送问题，导致使用一些国外软件如：whatsapp，Instagram等推送造成了很大的延迟和困扰。 使用surfboard的时候发现只要锁屏情况之下，以上聊天软件就不会再推送信息，除非点进APP之后消息才会弹出来。 但是：shadowsrock，SSR等软件不会出现这个情况~ 通过测试之前的clash for Android 通过 在软件中添加hosts，把google的一些信息添加进去之后成功实现消息及时推送 除非是网络实在不太好的情况，轻微延迟。但绝对不会像之前那样只能通过点开APP才有信息。 请问Surfboard是否能否增加额外的hosts添加选项，就像CLASH那样是独立填写的，而不是写在配置文件或规则里。 谢谢~~

你好，请问安卓SSR连接FCM一分钟断一次有办法吗？手机是三星港版的

**Comment by sieyr** [comment]
你好，请问安卓SSR连接FCM一分钟断一次有办法吗？手机是三星港版的
