### ISSUE TITLE
安卓14系统，磁贴无法使用

### ISSUE THREAD

**Issue by cynide00** [getsurfboard/surfboard#174]
升级安卓14之后下拉栏磁贴失效，开起和关闭都没有效果，在oneui6.0和pixel 14系统上均存在此问题

**Comment by cynide00** [comment]
设置为点击之后自动收起通知栏之后可用，关闭这个选项之后不可用

**Comment by getsurfboard** [comment]
Android 14及以上系统不再支持"点击磁铁后不收起通知栏"

**Comment by getsurfboard** [comment]
下个版本修复此问题
