### ISSUE TITLE
新功能建议：分流设置排序 

### ISSUE THREAD

**Issue by WhiCCX0** [getsurfboard/surfboard#176]
增加分流设置排序按更新/安装时间排序。
这样对新安装的app进行分流设置会方便很多
![Screenshot_20231124-111636_Clash Meta for Android](https://github.com/getsurfboard/surfboard/assets/47388635/756f24fc-0ff5-4d25-861f-1fdaf7f63657)

**Comment by getsurfboard** [comment]
将在下个版本外放
