### ISSUE TITLE
wireguard协议没有预共享密钥这个字段吗

### ISSUE THREAD

**Issue by wustyu** [getsurfboard/surfboard#177]
我的wireguard一直通不了 怀疑是surfboard没有支持预共享密钥的问题presharedkey 请问是这个原因吗 查询了好多资料没有结果

**Comment by getsurfboard** [comment]
是的，目前还没有支持`preshared-key`参数

**Comment by wustyu** [comment]
> 是的，目前还没有支持`preshared-key`参数

### 大佬最近有计划更新这个参数吗
