### ISSUE TITLE
URL-TEST、URL覆写相关

### ISSUE THREAD

**Issue by KeSaite** [getsurfboard/surfboard#18]
URL-TEST：
软件是不是对配置文件中URL-TEST 组数量做了限制，我尝试过导入25个URL-TEST组的配置文件，汇报未知错误，查找了很久，发现删掉一半URL-TEST 组就可以正常导入了，这是什么原因

URL覆写：
作者，sagernet有一个域名覆写的功能，surfboard有计划支持吗？

**Comment by getsurfboard** [comment]
麻烦重现问题后提供日志

**Comment by KeSaite** [comment]
> 麻烦重现问题后提供日志

日志链接
https://linksharing.samsungcloudcn.com/h7mHdyoDQvlt
有效期至：2022年8月17日

**Comment by getsurfboard** [comment]
```
W System.err: java.lang.IllegalStateException: ProxyGroup Auto-SWE has no proxies inside
W System.err: 	at c.b.l(SourceFile:9)
W System.err: 	at q5.g.g(SourceFile:38)
W System.err: 	at q5.g$b.r(Unknown Source:14)
W System.err: 	at hh.a.s(Unknown Source:8)
W System.err: 	at wh.m0.run(Unknown Source:86)
W System.err: 	at bi.f.run(Unknown Source:12)
W System.err: 	at ci.j.run(Unknown Source:2)
W System.err: 	at ci.a$a.run(SourceFile:9)
```

**Comment by KeSaite** [comment]
为了方便以后，我给所有国家做了auto并做了正则表达式过滤节点，这样难免有些policy-path是空的，如果是因为这个是不是有些不太合理，我手动加了DIRECT正常了

未知错误的
> Auto-SWE = url-test policy-path=https://xx.com, policy-path=https://xxxx.com, update-interval=3600, policy-regex-filter=瑞典, interval=3600, tolerance=50, 
evaluate-before-use=true, hidden=true


正常的
> Auto-SWE = url-test, DIRECT, policy-path=https://xx.com, policy-path=https://xxxx.com, update-interval=3600, policy-regex-filter=瑞典, interval=3600, tolerance=50, hidden=true

**Comment by getsurfboard** [comment]
这种配置在Surge下正常吗？在group内没有proxy的时候，直接当DIRECT处理？

**Comment by KeSaite** [comment]
这个我也不清楚，从个人出发，机智不太合理吧

**Comment by getsurfboard** [comment]
目前不打算兼容空的代理组，还是先手动加Direct兼容吧
