### ISSUE TITLE
[Feature] 允许通过Intent外部控制

### ISSUE THREAD

**Issue by piledog** [getsurfboard/surfboard#184]
这将方便[Tasker](https://tasker.joaoapps.com/)等工具自动化管理

Ref:
> [Wireguard TunnelManager: new intents](https://git.zx2c4.com/wireguard-android/commit/?id=a2ccbf003cc10369c177a3a354558f903df44e39)

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/deeplink
