### ISSUE TITLE
最新版 2.23.0 最新版规则报错

### ISSUE THREAD

**Issue by uclort** [getsurfboard/surfboard#196]
![image](https://github.com/getsurfboard/surfboard/assets/17818831/bef5fc0f-9095-4872-874c-0b17651d6212)

```
Auto-香港 = url-test, include-other-group=Node-All, policy-regex-filter=香港, tolerance=30, hidden=true
Auto-台湾 = url-test, include-other-group=Node-All, policy-regex-filter=台湾, tolerance=30, hidden=true
Auto-日本 = url-test, include-other-group=Node-All, policy-regex-filter=日本, tolerance=30, hidden=true
Auto-美国 = url-test, include-other-group=Node-All, policy-regex-filter=美国, tolerance=30, hidden=true
Auto-OpenAI = url-test, include-other-group=Node-All, policy-regex-filter=日本|台湾|JP|TW, tolerance=30, hidden=true

Node-All = select, hidden=true, include-other-group="Node-Coo, Node-ST, Node-OwO"
Node-Coo = select, hidden=true, policy-path=https://
Node-ST = select, hidden=true, policy-path=https://
Node-OwO = select, hidden=true, policy-path=https://
```

**Comment by uclort** [comment]
2.22.9 版本正常使用，升级到 23 出现的问题

**Comment by uclort** [comment]
刚才重装 2.22.9 之后也提示同样的错误了。

**Comment by uclort** [comment]
发现是把 Auto 的 include-other-group 换成 Coo 或者 ST OwO 都可以，只要用 Node-All 就是不行的，是因为嵌套了多层 include-other-group 么？

**Comment by getsurfboard** [comment]
请私聊发送配置到 getsurfboard@gmail.com 进行调试

**Comment by uclort** [comment]
> 请私聊发送配置到 [getsurfboard@gmail.com](mailto:getsurfboard@gmail.com) 进行调试

已发送，uclort@gmail.com.

**Comment by getsurfboard** [comment]
已邮件回复修改后的配置文件，修改点是：把被引用的节点组写在前面，这样能先被解析并且被后面的节点引用到

**Comment by uclort** [comment]
> 已邮件回复修改后的配置文件，修改点是：把被引用的节点组写在前面，这样能先被解析并且被后面的节点引用到

感谢，试过了，调整顺序后确实可以了，但是这是个优化点，正常来说不应该有顺序上的区分，如果区分顺序的话节点订阅就要写到上面，否则截图中的 OpenAI 策略组还是有问题的，现在只能抓到 Auto-OpenAI，include-other-group=Node-All 并不能抓到指定节点。

**希望能优化一下这个地方，忽略顺序**

![CleanShot 2024-01-21 at 16 49 49](https://github.com/getsurfboard/surfboard/assets/17818831/e0f0d6ed-453e-45de-8fa9-78cc7d1b9c48)

**Comment by getsurfboard** [comment]
按照顺序原则，把所有Node-XX组调整到最上面，OpenAI组就可以显示出多个节点了

优化顺序问题暂时来说没那么好改，短时间内没办法完成，先暂时用这种方式来兼容吧

**Comment by uclort** [comment]
> 按照顺序原则，把所有Node-XX组调整到最上面，OpenAI组就可以显示出多个节点了
> 
> 优化顺序问题暂时来说没那么好改，短时间内没办法完成，先暂时用这种方式来兼容吧

好的。💪

**Comment by getsurfboard** [comment]
@uclort 请尝试最新的2.23.4版本
