### ISSUE TITLE
配置文件导入失败

### ISSUE THREAD

**Issue by zer0cod3** [getsurfboard/surfboard#199]
![Screenshot_20240113_204706_com getsurfboard](https://github.com/getsurfboard/surfboard/assets/82299437/5d270781-f523-4f37-9ae9-3875e30bf1df)

扫描二维码导入 或者 手动粘贴URL订阅地址 都得到上面的提示 | Surfboard：2.23.1 [Latest]

**Comment by HuangRunzhe** [comment]
换一个机场，机场的问题

**Comment by HuangRunzhe** [comment]
给你试试我的https://hi.gdnode.cc/api/v1/client/subscribe?token=60abafb54aac40978aead5953d92e39e
