### ISSUE TITLE
开放监听端口以供 Adguard 等工具进行共存、代理过滤广告流量

### ISSUE THREAD

**Issue by stars-island** [getsurfboard/surfboard#20]
如题，就像其它一些竞品，例如 Clash for Android ，开放默认的监听端口，可以让 Adguard 设置 Proxy 代理流量，以达到实现两者共存，并且过滤广告的效果。

类似实现共存的过程如下所示，基本上实现方案是 建立 proxy ，连接 127 本地地址 + 监听端口 ：

 - https://blog.ichr.me/post/adguard-with-clash/

 - https://www.adgk.net/posts/52/

我在网上找了好久，找不到 surfboard 默认监听端口相关的文章，自己看了半天规则文本，也看不到有写 port 的字段。如果本身就有监听端口的话，可以说明一下吗？谢谢！

更新：找到了设置，里面有本地代理的默认端口，这个小问题解决了。但是尚不知道怎么设置才能仅让 surfboard 启动而不代理全局流量。

**Comment by getsurfboard** [comment]
暂不支持

**Comment by happmaoo** [comment]
> 如题，就像其它一些竞品，例如 Clash for Android ，开放默认的监听端口，可以让 Adguard 设置 Proxy 代理流量，以达到实现两者共存，并且过滤广告的效果。
> 
> 类似实现共存的过程如下所示，基本上实现方案是 建立 proxy ，连接 127 本地地址 + 监听端口 ：
> 
> * https://blog.ichr.me/post/adguard-with-clash/
> * https://www.adgk.net/posts/52/
> 
> 我在网上找了好久，找不到 surfboard 默认监听端口相关的文章，自己看了半天规则文本，也看不到有写 port 的字段。如果本身就有监听端口的话，可以说明一下吗？谢谢！
> 
> 更新：找到了设置，里面有本地代理的默认端口，这个小问题解决了。但是尚不知道怎么设置才能仅让 surfboard 启动而不代理全局流量。

在哪设置啊找不到
