### ISSUE TITLE
socket5无密码认证该怎么设置？

### ISSUE THREAD

**Issue by piaoapiao** [getsurfboard/surfboard#203]
Srelay 默认没提供密码认证，内网搭建

参考: https://getsurfboard.com/docs/profile-format/proxy/external-proxy/socks5/

但是主要说的是有账号密码的，无密码的尝试多种情况，没有成功，是不是不支持无密码socket5？

ProxySOCKS5 = socks5, 10.57.242.82, 1080, username, password, udp-relay=false 

ProxySOCKS5 = socks5, 10.57.242.82, 1080,,, udp-relay=false 

ProxySOCKS5 = socks5, 10.57.242.82, 1080, , , udp-relay=false 

ProxySOCKS5 = socks5, 10.57.242.82, 1080, “”, “”, udp-relay=false   
尝试多种方式，都没成功，可以提供一个 参考 ？ 谢谢！

**Comment by getsurfboard** [comment]
ProxySOCKS5 = socks5, 10.57.242.82, 1080, udp-relay=false
