### ISSUE TITLE
全局模式下只能选择 [Proxy] 下的本地节点

### ISSUE THREAD

**Issue by uclort** [getsurfboard/surfboard#204]
开启全局后 [Proxy Group] 全部不显示，只剩下 [Proxy] 下的本地节点，无法正常使用全局模式

![WechatIMG287](https://github.com/getsurfboard/surfboard/assets/17818831/0d08e299-c86a-4b05-8d6a-eaaa304d920e)

另外可否加一个开关，展示 hidden 的策略组，有一些频率低的策略组，默认 hidden = true，偶尔可能会需要配置一下，希望可以在下方面板上有一个开关，iOS 上 Surge 是有这个功能。

![WechatIMG288](https://github.com/getsurfboard/surfboard/assets/17818831/e8e75a30-ef25-4070-8e0b-fcc184be7803)

**Comment by uclort** [comment]
全部模式的问题是策略组 hidden=true 引起的，我的配置文件已经发送到 getsurfboard@gmail.com，发送人 uclort@gmail.com (issue: #196)，把 Node-All、Node-ST、Node-OwO、Node-Coo 四个策略组 hidden=true，即可复现，辛苦作者一块调试一下。

**Comment by Moriarty6086** [comment]
也遇到这个问题了，如果节点全部是远程配置且全都hidden=true，那么global模式就一个节点都没有了。
能出一个专门设置global节点的功能吗

**Comment by getsurfboard** [comment]
会在下个版本修改成global mode也展示hidden组的代理
