### ISSUE TITLE
SUBNET,SSID 不能触发指定规则

### ISSUE THREAD

**Issue by WuhanSy** [getsurfboard/surfboard#207]
![image](https://github.com/getsurfboard/surfboard/assets/23512897/8a021593-8947-4ff6-95ca-16851cca298c)

连接指定wifi并不能触发DIRECT规则，是我的理解有问题吗？

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/rule/subnet

不需要加双引号

**Comment by WuhanSy** [comment]
ok,已解决，习惯surge格式了，谢谢

**Comment by getsurfboard** [comment]
https://manual.nssurge.com/rule/subnet.html

Surge格式也是这样定义的，可能Surge做了双引号的兼容
