### ISSUE TITLE
公网ip一直转圈，无法正常使用

### ISSUE THREAD

**Issue by sygiegiehs** [getsurfboard/surfboard#208]
![20240126100212](https://github.com/getsurfboard/surfboard/assets/124494789/138a8ac5-38cc-442e-baed-d9a3517edd5a)
翻出不去，梯子本身没炸

**Comment by getsurfboard** [comment]
WSA?

**Comment by dimsky** [comment]
+1 蜂窝网络会有这个问题。

**Comment by Yerosius** [comment]
Surfboard本身实现依赖于VPNService接口，检查系统是否支持

**Comment by sygiegiehs** [comment]
> WSA?

是的

**Comment by sygiegiehs** [comment]
> +1 蜂窝网络会有这个问题。

如何解决

**Comment by sygiegiehs** [comment]
之后在WSA用clash for android,能正常使用，但surfboard不可以

**Comment by sygiegiehs** [comment]
我放弃了。
