### ISSUE TITLE
Why is my public IP always China?

### ISSUE THREAD

**Issue by Slayemus** [getsurfboard/surfboard#210]
I can access other websites such as github/YouTube, but surfboard shows that my public IP is always China
![Screenshot_20240129-152618_Chrome](https://github.com/getsurfboard/surfboard/assets/137778514/495778f9-cb51-4596-a45a-8a4ae39392cf)

**Comment by getsurfboard** [comment]
public ip is fetched using FINAL rule, if no FINAL defined, DIRECT is used.
