### ISSUE TITLE
关于使用SUBNET规则的一些问题

### ISSUE THREAD

**Issue by MuXia-0326** [getsurfboard/surfboard#212]
使用场景：使用SUBNET指定SSID为家里无线名字，回家让手机的流量全部走直连，交给软路由去进行代理处理

出现情况：surfboard转发给软路由的请求全是ip，是软路由上的openclash无法走规则，关闭surfboard后恢复正常

不知是不是因为surfboard先用dns解析的请求，在进行转发的原因，不知作者能否处理一下这种情况

版本：2.23.4

**Comment by getsurfboard** [comment]
surfboard转发给软路由的请求全是ip

这句话应该如何理解？

**Comment by MuXia-0326** [comment]
> surfboard转发给软路由的请求全是ip
> 
> 这句话应该如何理解？

就是我看软路由上openclash的日志，来源请求都是纯ip，关掉surfboard请求就变成域名了

**Comment by getsurfboard** [comment]
> Author

有可能你的软路由是依赖dns请求记录来还原域名的，而Surfboard的配置或者设置中启用了DoH，导致可被解析的UDP 53包消失。

**Comment by MuXia-0326** [comment]
> 有可能你的软路由是依赖dns请求记录来还原域名的，而Surfboard的配置或者设置中启用了DoH，导致可被解析的UDP 53包消失。
好的
