### ISSUE TITLE
平板上横屏查看配置文件会不显示内容，竖屏正常

### ISSUE THREAD

**Issue by Pleiadem** [getsurfboard/surfboard#214]
![Screenshot_2024-02-12-10-43-14-100_com getsurfboard-edit](https://github.com/getsurfboard/surfboard/assets/90079093/2d5831c0-a1ff-4dc1-9dd2-54fcc4b481da)
![Screenshot_2024-02-12-10-43-48-504_com getsurfboard-edit](https://github.com/getsurfboard/surfboard/assets/90079093/1c0e962d-d85b-44c3-9102-90bdf22fa140)
如题，设备是小米平板5pro

**Comment by ezatgz** [comment]
Same here. Xiaomi pad 5.

**Comment by getsurfboard** [comment]
Will be fixed in next release.
