### ISSUE TITLE
功能建议：支持IPV6

### ISSUE THREAD

**Issue by Nelocompne** [getsurfboard/surfboard#22]
subconverter 配置转换中 surfboard 的默认设置是：
```ini
[General]
ipv6 = false
```
希望 surfboard 能够在 覆盖配置文件定义项 中添加ipv6启用开关。

**Comment by jacksunhack** [comment]
ipv6的dns 添加格式是啥样的 又没有模板

**Comment by Nelocompne** [comment]
> ipv6的dns 添加格式是啥样的 又没有模板

参考：
- https://github.com/getsurfboard/manual/blob/main/docs/profile-format/overview.md
- https://manual.nssurge.com/dns/dns-override.html

```ini
[General]
ipv6 = true
dns-server = system, [2001:dc7:1000::1]:53
```

文档说遵循Surge的配置格式，Surge表示：
> “When IPv6 is available and enabled, Surge DNS client will send both A and AAAA questions to upstream DNS Servers. The first A or AAAA answer returned will be used.”

所以我认为不管surfboard支不支持ipv6，也都应该要提供这种支持，即使它是未来的一项计划。

**Comment by getsurfboard** [comment]
Surfboard暂不支持IPV6
