### ISSUE TITLE
为何我的app没有代理按钮？

### ISSUE THREAD

**Issue by DescartHsu** [getsurfboard/surfboard#228]
安装的最新版2.24.1，但界面下方只有仪表盘，配置，和工具，没有代理选项，无法选择线路，卸了重装也是一样，咋回事？

**Comment by Icarus-9** [comment]
同问，有结果吗

**Comment by ridesheep135** [comment]
同问，有结果嘛？

**Comment by ridesheep135** [comment]
找到结果了！因为出站模式选择了直连，选择规则就好了

**Comment by getsurfboard** [comment]
https://github.com/getsurfboard/surfboard/issues/254

**Comment by DescartHsu** [comment]
> 找到结果了！因为出站模式选择了直连，选择规则就好了

后来我发现是没连，点击连接后就显示了
