### ISSUE TITLE
Can't connect to FCM when turn on the bypass mode

### ISSUE THREAD

**Issue by QianYushi** [getsurfboard/surfboard#229]
![img1](https://github.com/getsurfboard/surfboard/assets/40188015/c3277057-661d-4c40-a7c4-732dd7904c3b)
![img2](https://github.com/getsurfboard/surfboard/assets/40188015/852229ab-2d1c-4b0f-9986-d22f3b552300)

I'm using Samsung S24 ultra, SM-9280 (China mainland's version), I can receive notifications from FCM server when connected to the VPN, but when the bypassable mode turned on, the FCM Diagnostics page shows not connected.

**Comment by getsurfboard** [comment]
Maybe FCM will bypass VPN if bypass mode available.
