### ISSUE TITLE
请求大佬更新鸿蒙NEXT版本

### ISSUE THREAD

**Issue by CGangel** [getsurfboard/surfboard#250]
目前用过的最好用的梯子软件，希望跟进鸿蒙next
能上架应用商城最好，不能上架也没关系，只要把安装包开发出来，大家可以自己注册开发者账号，自己签名侧载

**Comment by burycreek** [comment]
能上架应用商城最好，不能上架也没关系
你在想什么奇奇怪怪的事...
我毫不怀疑华为对VPN类型的监控力度

**Comment by dgh1818** [comment]
同希望能尽早有next版本，最好能上架外区appgallery

**Comment by weishubaoforwork** [comment]
NEXT？JS开发梯子简直。有点奇奇怪怪

**Comment by YinsenHo** [comment]
这是要自首啊

**Comment by qigithub** [comment]
next上架app, 要开发者实名认证的(手机号和身份证),还上架,怕不是疯了

**Comment by dgh1818** [comment]
> next上架app, 要开发者实名认证的(手机号和身份证),还上架,怕不是疯了

上不上架是次要的 主要是我都是拿这软件翻回家看nas 现在web不能暴露在公网上

**Comment by CGangel** [comment]
不上架也行，把安装包开发出来就好，用户只要注册开发者账号，就可以自签名，以调试的名义安装



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月27日(周二) 下午5:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getsurfboard/surfboard] 请求大佬更新鸿蒙NEXT版本 (Issue #250)




 
next上架app, 要开发者实名认证的(手机号和身份证),还上架,怕不是疯了

**Comment by websokit** [comment]
上架外区也可以
