### ISSUE TITLE
希望这个位置在增加个节点测试按钮，方便在电视使用，这个截图是clash meta  ，或者在设置里，单独增加个开关，只要回到节点选择界面，自动检测节点

### ISSUE THREAD

**Issue by dl250** [getsurfboard/surfboard#252]
![photo_2024-07-13_06-28-27](https://github.com/user-attachments/assets/da049607-c6cf-4a6e-987d-6afd1f5e5ada)

**Comment by getsurfboard** [comment]
请使用专属的TV版本

https://github.com/getsurfboard/surfboard/releases/tag/tv-1.0.2
