### ISSUE TITLE
期待增加代理节点过滤功能

### ISSUE THREAD

**Issue by blueisacat** [getsurfboard/surfboard#257]
当节点比较多时测速和选择比较麻烦，过滤功能可根据节点名称过滤，测速也只是对已过滤出来的节点进行测速，缩短测速时间，提升使用体验

**Comment by getsurfboard** [comment]
使用policy-regex-filter

https://getsurfboard.com/docs/profile-format/proxygroup/select

**Comment by blueisacat** [comment]
感谢回复，以我的理解，policy-regex-filter是通过修改配置文件的方式来进行过过滤，需要对配置文件进行编辑，能否在软件层面提供一个过滤功能，或者类似mixin的方式。

**Comment by getsurfboard** [comment]
如果以配置外过滤来做，无法确保逻辑严谨性，比如说出现命中规则后对应的代理无法被找到等情况

Blue是只蓝色的猫 ***@***.***> 于 2024年8月9日周五 17:42写道：
