### ISSUE TITLE
webdav无法从alist下拉文件

### ISSUE THREAD

**Issue by TPAXcc** [getsurfboard/surfboard#259]
原因是alist没有写webdav前端 但是webdav本身是正常的

**Comment by TPAXcc** [comment]
![Screenshot_2024-08-16-02-38-35-727_com.getsurfboard.jpg](https://github.com/user-attachments/assets/a77b5894-5590-4061-be7c-48b8dc22e73e)

**Comment by getsurfboard** [comment]
经过测试可以兼容alist webdav，填写服务器地址时，path需要完整到具体的挂载点，例如/dav/alidrive，如果只写/dav，这个挂载点是无直接的写入权限的
