### ISSUE TITLE
TV 版在电视安装后不显示应用图标

### ISSUE THREAD

**Issue by wha4up** [getsurfboard/surfboard#260]
平台：TCL
安卓系统版本：不清楚
应用版本：tv-1.0.0
问题：
安装后我的应用中无应用图标，卸载中也找不到应用。
确认有提示安装成功，在其他可显示已安装应用中也可以看到。

**Comment by wha4up** [comment]
tv-1.0.1点击设置闪退

**Comment by getsurfboard** [comment]
https://github.com/getsurfboard/surfboard/releases/tag/tv-1.0.2
