### ISSUE TITLE
[Feature Request] 是否可以提供快捷开关或桌面widget

### ISSUE THREAD

**Issue by AaronW-BE** [getsurfboard/surfboard#270]
长按App开启代理，或桌面小组件开关代理

**Comment by CraigMChen** [comment]
同求桌面小组件一键开关

**Comment by CraigMChen** [comment]
@AaronW-BE 请问为什么要关闭 issue，是现在已经支持桌面小组件开关了吗

**Comment by AaronW-BE** [comment]
> @AaronW-BE 请问为什么要关闭 issue，是现在已经支持桌面小组件开关了吗

对的，已经有了，长按图标已经有开启/关闭的快捷菜单了，可以将这个按钮单独拖到桌面（不知道是不是Android14的功能）

@CraigMChen
