### ISSUE TITLE
Surfboard在Pixel 9Pro（Android 15正式版）系统下闪退严重，望修复、兼容&改进。

### ISSUE THREAD

**Issue by seoho8908** [getsurfboard/surfboard#275]
Surfboard在Pixel 9Pro XL（Android 15正式版）系统下闪退严重，望修复、兼容&改进。

**Comment by Yana-Hangabina** [comment]
在HyperOS 2（Android 15）上同闪退，包括应用分流设置页等

**Comment by YipSzeho** [comment]
在HyperOS 1.1（Android 15）上同闪退，包括分流设置、外部资源管理等。
