### ISSUE TITLE
是否支持 Surge 配置文件的 “配置段分离” ？

### ISSUE THREAD

**Issue by PositionZer0** [getsurfboard/surfboard#29]
如 https://community.nssurge.com/d/506-detached-profile-section 提到的：  
```
[Proxy]
#!include Proxy.dconf
```
  
自己试了一下，Surfboard 似乎不支持这一功能。  
如果不支持，有没有办法只引用服务商托管配置的 [Proxy] 和 [Proxy Group] 段，而自行编写其他段？

**Comment by Kingsmanvn-Official** [comment]
@PositionZer0 I see in Clash for Android there is a similar `proxy-providers` feature at your disposal.
You can check out the documentation here: https://github.com/Dreamacro/clash/wiki/configuration#proxy-providers

**Comment by king1x32** [comment]
@PositionZer0 Similar feature `External Group`
you can use instead
You can check out the documentation here: https://manual.nssurge.com/policy/group.html

**Comment by getsurfboard** [comment]
You can use `policy-path` in ProxyGroup: https://getsurfboard.com/docs/profile-format/proxygroup/select

"You can use a profile url as policy path url, only proxies defined in [Proxy] section will be used"
