### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 565465474575** [getsurfboard/surfboard#4]
请求加入节点去重功能

**Comment by getsurfboard** [comment]
什么场景下会发生节点重复？

**Comment by 565465474575** [comment]
> 什么场景下会发生重复？

因为部分订阅连接里的节点会有一样的像节点池

**Comment by bowzhung** [comment]
> > 什么场景下会发生重复？
> 
> 因为部分订阅连接里的节点会有一样的像节点池

订阅转换器了解下
