### ISSUE TITLE
[Feature] Support for trojan-go import

### ISSUE THREAD

**Issue by rezaf28** [getsurfboard/surfboard#47]
Hi
Please Support Trojan-go url.
EXP:
trojan-go://password@my.domain.com:443/?type=ws&sni=*.domain.com&host=my.domain.com&path=%2Fws#Remark

* Please Support ws url import : type=ws and host and path

thanks

**Comment by getsurfboard** [comment]
Sorry, no plan for that, just want to be consistent with Surge.

**Comment by getsurfboard** [comment]
Trojan with ws is already supported, pls just follow the profile standard.

https://getsurfboard.com/docs/profile-format/proxy/external-proxy/trojan

**Comment by rezaf28** [comment]
I know, but IMPORT FROM URL Not Work
