### ISSUE TITLE
自动更新

### ISSUE THREAD

**Issue by Pylogmon** [getsurfboard/surfboard#5]
可以添加定时自动更新订阅的功能吗

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/managed_config

**Comment by ambition-echo** [comment]
> https://getsurfboard.com/docs/profile-format/managed_config

更新时间最低限度是12h吗，跟文档写的不一样啊，我写的3600保存之后就自动变成43200了

**Comment by getsurfboard** [comment]
查询代码之后没有发现有hardcode 43200的地方，是不是你远端的配置内容还是43200的，更新配置被刷回去了？
