### ISSUE TITLE
可以设置多少分钟后自动跟新订阅吗？

### ISSUE THREAD

**Issue by m-lxc** [getsurfboard/surfboard#50]
你好：
找了设置没找到想要的功能。
订阅更新，只有订阅那手动更新功能，或者断开连接重新连上才自动更新订阅。
能否在连上的状态下，设置多少分钟后自动更新订阅？类似clash那样，配置那有选择多少时间更新一次。
谢谢！

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/managed_config
