### ISSUE TITLE
希望在有设置doh的情况下，提供关闭默认dns查询的选项

### ISSUE THREAD

**Issue by ghost** [getsurfboard/surfboard#51]
你好，我在查看logcat的时候发现，在设置里doh服务器的情况下，一次连接的dns查询过程中，surfboard会同时向doh 和默认dns(我设置为223.5.5.5)发起查询。我的想法中，默认dns只用于查询doh中的域名，而不是每次连接的域名。这样导致最终访问的域名还是发给了223.5.5.5，虽然它可能没有发挥任何作用，但我希望我的dns查询只发送给doh服务器，以保护隐私。希望能提供关闭默认dns查询的功能。

以下为该logcat输出:
11-19 11:05:40.284 27931-28051/
(0 x0000002E) DNS QUERY(0) UNKNOWN 
[www.gstatic.com] using doh-server
11-19 11:05:40.284 27931-28051/
(0 x0000002E) DNS QUERY(0) UNKNOWN [www.gstatic.com] using 223.5.5.5:53

**Comment by getsurfboard** [comment]
这是一个日志的问题，实际表现是符合你的预期的，下个版本会修复日志问题，即在走了doh的情况下依然打印dns日志
