### ISSUE TITLE
Cannot reach test delay floating button in proxies list with remote on android tv (chromecast)

### ISSUE THREAD

**Issue by shenghan97** [getsurfboard/surfboard#59]
When I use the direction pad remote on my chromecast with android tv, I cannot reach to the test delay floating action button in global mode at the bottom right corner of the screen. 

The start and stop floating button in the dashboard works fine with direction pad remote, I can simply scroll to the bottom to select and interact with it. But when I try to scroll to the bottom of the proxy list view, I can't reach the delay testing floating button no matter what direction I click. 

Thanks for the great effort you out in this app and hope it gets only better!

**Comment by getsurfboard** [comment]
I can reproduce this issue, still looking for a way to fix this. Maybe I will avoid using floating button on tv devices.

**Comment by getsurfboard** [comment]
Fix will be released in 2.19.2

**Comment by shenghan97** [comment]
Fantastic!

Thank you for the quick fix.
