### ISSUE TITLE
希望能添加一个自动更新配置的功能。。。

### ISSUE THREAD

**Issue by Ingress007** [getsurfboard/surfboard#68]
希望能添加一个自动更新配置的功能，还有就是覆盖配置文件里面的订阅链接，因为有时候买的机场给的订阅链接是没问题可以下载配置，但是下载下来的配置文件里的订阅链接却是错的

**Comment by OSNewbie** [comment]
有自动更新配置功能，在设置，应用，倒数第二项就是，建议开代理，更新配置，我或者订阅链接，他就不会出错，一般不会下载错 除非你重置了订阅链接或者机场提供的订阅链接，如果更新错误，一般报返回错误，可能是在维护，
