### ISSUE TITLE
分流设置下的应用列表读取不全，有的app无法显示。

### ISSUE THREAD

**Issue by CraftX2025** [getsurfboard/surfboard#71]
分流设置下的应用列表读取不全，有的app无法显示。
安装低版本也是如此 v2.14.0，v2.18.8
OPPO ColorOS 12

**Comment by CraftX2025** [comment]
刚刚加载配置文件后，有的未出现的应用出现了。单还是没有全部显示出来。

**Comment by getsurfboard** [comment]
可以尝试切换一下分流设置右上角的一些勾选开关
