### ISSUE TITLE
请问surfboard为什么比其他软件（v2rayNG/clash）更快呢？

### ISSUE THREAD

**Issue by Killerkk** [getsurfboard/surfboard#72]
想了解其中原理，如果能有大佬回复，非常感谢！

**Comment by getsurfboard** [comment]
并没有吧，如何得出这样一个结论呢？

如果是Youtube上看的一个测试视频的话，那个已经是很老的视频了。后面Clash都进行了更新，目前性能上我觉得是没有什么区别的。

**Comment by Killerkk** [comment]
感谢回答，了解了，那我还是自己实践一下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 凌晨0:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getsurfboard/surfboard] 请问surfboard为什么比其他软件（v2rayNG/clash）更快呢？ (Issue #72)





 
并没有吧，如何得出这样一个结论呢？
 
如果是Youtube上看的一个测试视频的话，那个已经是很老的视频了。后面Clash都进行了更新，目前性能上我觉得是没有什么区别的。
