### ISSUE TITLE
[BUG] Trojan Not Working!

### ISSUE THREAD

**Issue by rezaf28** [getsurfboard/surfboard#74]
Hello
Trojan will not work with your default Profile settings when importing with a "Import from url".
For example, it does not work in the following file:
[TrojanProfile.txt](https://github.com/getsurfboard/surfboard/files/10420216/TrojanProfile.txt)

but working in this File:
[TrojanProfile2.txt](https://github.com/getsurfboard/surfboard/files/10420232/TrojanProfile2.txt)

thanks

**Comment by getsurfboard** [comment]
I don't see any rule in your profile 'TrojanProfile2.txt', it will make it work like an empty profile.

Can you describe in detail how 'not working' behaves?

Btw, surfboard does not fully support trojan-go, it only support trojan protocol.
