### ISSUE TITLE
[Feature]  Surfboard Profile sharing new options

### ISSUE THREAD

**Issue by rezaf28** [getsurfboard/surfboard#75]
Hi
Thank you for your efforts for the software.
Please make it possible to share profile files in BASE64 format and QRCODE.
For Exp:
[TrojanProfile2.txt](https://github.com/getsurfboard/surfboard/files/10420250/TrojanProfile2.txt)
Encoding this file texts to base64 and merge with "surfboard://"
and Result for sharing with SMS:

`surfboard://W1Byb3h5XQpUcm9qYW4tR28gPSB0cm9qYW4sIHdzLnRlc3QuY29tLCA0NDMsIHBhc3N3b3JkPTEyMzQ1Njc4OTAsIHdzPXRydWUsIHdzLXBhdGg9L3dzLCBza2lwLWNlcnQtdmVyaWZ5PWZhbHNlLCB1ZHAtcmVsYXk9ZmFsc2UsIHdzLWhlYWRlcnM9SG9zdDp3cy50ZXN0LmNvbQoKW1Byb3h5IEdyb3VwXQpTZWxlY3RHcm91cCA9IHNlbGVjdCwgVHJvamFuLUdv`

and other users can import that with "Import from URL"

or convert to qrcode:
![qrcode](https://user-images.githubusercontent.com/25824853/212543402-c9ab49a0-08f2-4c5b-b10a-afd3cb99aa0a.png)

and other users scan that.

**Comment by getsurfboard** [comment]
Why not just share your profile as a file?

**Comment by rezaf28** [comment]
Because we cannot send the file by SMS, And MMS and other social networks like WhatsApp are Blocked in Iran!

**Comment by getsurfboard** [comment]
It is not feasible to use base64 format to transmit profile content, base64 will significantly increase the content size, and the URI format has a length limit, especially when you want to bind a custom scheme uri.

I recommend changing the profile to online profile and sharing the profile import uri link via SMS.

**Comment by rezaf28** [comment]
ok, thanks.
I can Solve this if you Solve that:
https://github.com/getsurfboard/surfboard/issues/74

I can share original Trojan URL but your default rules is extra(for China only) and not Global.
thanks again

**Comment by getsurfboard** [comment]
Let's talk about it in #74
