### ISSUE TITLE
[Feature Request] 能否增加自动更新自定URL的GeoIP数据库功能？

### ISSUE THREAD

**Issue by tigerchen1998** [getsurfboard/surfboard#76]
增加一个默认的更新周期或者自定更新周期，或者每次启动时更新都可以

**Comment by getsurfboard** [comment]
https://getsurfboard.com/docs/profile-format/managed_config

**Comment by tigerchen1998** [comment]
> https://getsurfboard.com/docs/profile-format/managed_config

作者你好，我指的并不是订阅链接，而是在自定GeoIP数据库这里增加一个自动更新的功能
![photo_2023-01-16_10-44-44](https://user-images.githubusercontent.com/64186000/212587730-3b77a947-6bc3-468b-b84b-6f807ee8b64e.jpg)

**Comment by getsurfboard** [comment]
geoip library file now be updated in every 24 hours
