### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by YYQK0113** [getsurfboard/surfboard#77]
![Screenshot_2023-01-19-18-30-41-870_com getsurfboard](https://user-images.githubusercontent.com/82374296/213428207-68964049-4744-4b50-8bb1-a994d025f8e4.jpg)
![IMG_20230119_183312](https://user-images.githubusercontent.com/82374296/213428214-9340f280-99d3-4fd3-a82e-542c825cd933.jpg)
上述图片中，剩余流量应该改为使用流量，剩余流量显示可能有误

**Comment by getsurfboard** [comment]
对话框文字内容是配置提供方决定的，并不是app自身决定
