### ISSUE TITLE
订阅信息中剩余流量显示错误

### ISSUE THREAD

**Issue by suprelory** [getsurfboard/surfboard#79]
最新版本2.20.0中
订阅信息中剩余流量显示错误
![IMG_20230122_080601.jpg](https://user-images.githubusercontent.com/56546578/213894859-c8acdd20-3735-4b48-ac08-1f5aca34feb3.jpg)
如图，剩余流量显示成了已用总流量

**Comment by OSNewbie** [comment]
这个与代理工具无关，能显示订阅信息就不错，具体流量你得去，机场的控制面板查看已用的流量
