### ISSUE TITLE
把通知栏划下来 surfboard 的磁贴会变灰色，然后马上变回正常颜色

### ISSUE THREAD

**Issue by Abettoe** [getsurfboard/surfboard#81]
手机一加 9pro，系统 ColorOs13
![Screenshot_2023-02-07-08-48-01-43_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/26241099/217120584-9862e2da-7789-42ab-a946-6732c4c3fd76.jpg)
![Screenshot_2023-02-07-08-57-48-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/26241099/217121264-2bcdc87c-c497-4042-998f-458f7984bfd4.jpg)

**Comment by getsurfboard** [comment]
It works as intended.
