### ISSUE TITLE
导入订阅时发生错误

### ISSUE THREAD

**Issue by ldgks** [getsurfboard/surfboard#82]
报错信息：java.lang.IllegalArgumentException: Decode url-test ProxyGroup but url is not http scheme: https://www.gstatic.com/generate_204

**Comment by getsurfboard** [comment]
将配置中的测速url从https改成http即可

**Comment by ldgks** [comment]
url测试可以增加支持https么？订阅源的测试url用户怎么改？

**Comment by getsurfboard** [comment]
> url测试可以增加支持https么？订阅源的测试url用户怎么改？

目前的技术选型不方便支持https呢
