### ISSUE TITLE
prepare vpn service failed

### ISSUE THREAD

**Issue by 5700x** [getsurfboard/surfboard#84]
i install this app in win 11 (windeows sub system) when i want start proxy give me error "prepare vpn sevice failed"
pls resolve this error.
![Untitled](https://user-images.githubusercontent.com/24326383/219828057-fd427800-4c46-4c2e-9b6b-573c84f2a3d3.jpg)

**Comment by getsurfboard** [comment]
Try this command in adb shell:

appops set com.getsurfboard ACTIVATE_VPN allow
