### ISSUE TITLE
建议添加 检查APP版本更新 的功能

### ISSUE THREAD

**Issue by alex14563** [getsurfboard/surfboard#85]

**Comment by yolomc** [comment]
设置里有个检查更新，点击后会跳转github release页面，但是没有自动下载和更新的功能。

**Comment by alex14563** [comment]
> 设置里有个检查更新，点击后会跳转github release页面，但是没有自动下载和更新的功能。

能问一下在哪儿么，始终没找到。
![Screenshot_20230301_164543.jpg](https://user-images.githubusercontent.com/19344483/222088902-2ba8d1e6-7a54-4858-b153-33ea16460c50.jpg)

**Comment by yolomc** [comment]
> > 设置里有个检查更新，点击后会跳转github release页面，但是没有自动下载和更新的功能。
> 
> 能问一下在哪儿么，始终没找到。 ![Screenshot_20230301_164543.jpg](https://user-images.githubusercontent.com/19344483/222088902-2ba8d1e6-7a54-4858-b153-33ea16460c50.jpg)

之前是有的，在“应用版本”和“更新说明”之间，不知道这个版本为啥不见了🤔

**Comment by getsurfboard** [comment]
通过GP安装的话是不会github release下载更新的，避免违反GP协议规则

**Comment by alex14563** [comment]
> 通过GP安装的话是不会github release下载更新的，避免违反GP协议规则

我是通过GitHub release下载安装的

**Comment by petcat** [comment]
这不是问题，你应该用play商店版本
