### ISSUE TITLE
Vmess AEAD 节点不可用？

### ISSUE THREAD

**Issue by RimuruChan** [getsurfboard/surfboard#88]
无法连接

**Comment by OSNewbie** [comment]
首次启动会有一个VPN请求，授权要点击确认
wmes 协议是支持的，请查，看分流设置那里的，是否有勾选走代理的应用？走规则模式，建议设置DNS/DOH服务器

**Comment by wzry2580** [comment]
首次启动会有一个VPN请求，授权要点击确认
wmes 协议是支持的，请查，看分流设置那里的，是否有勾选走代理的应用？走规则模式，建议设置DNS/DOH服务器
