### ISSUE TITLE
[BUG] 从2.12.4版本开始通知栏瓷贴不可用

### ISSUE THREAD

**Issue by Oosl** [getsurfboard/surfboard#9]
### 有问题的版本：  
2.12.4 - latest
### 问题描述：  
从版本2.12.3开始，通知栏快捷瓷贴就异常了。之前版本添加的瓷贴一直灰色，不会响应应用的行为。
一旦从通知栏移除已添加的瓷贴，就无法在瓷贴列表里抓到surfboard 提供的瓷贴，我查看changlog也并没有看到有关去除/修改瓷贴的相关描述
### 预期行为：  
通知栏瓷贴可正常添加并正常使用

**Comment by getsurfboard** [comment]
请问使用了这个版本了吗？

https://github.com/getsurfboard/surfboard/releases/tag/2.13.4

**Comment by Oosl** [comment]
我去，你好快。
用过了，提Issue之前为了定位问题出现的版本，二分定位尝试了很多版本。包括今天的最新版

**Comment by getsurfboard** [comment]
麻烦提供下你的手机型号/品牌/系统版本信息

**Comment by Oosl** [comment]
手机品牌及型号：一加9 Pro
安卓系统：安卓12
厂商系统：Color OS 12.1 C.65

**Comment by getsurfboard** [comment]
2.13.4我就是用colorOS测试过的，你是否试过重新添加，或者卸载重装等操作？

**Comment by Oosl** [comment]
刚测试，卸载重装2.13.4之后正常了，直接覆盖升级安装不可以。感谢~
