### ISSUE TITLE
导入url提示网络错误：HTTP0

### ISSUE THREAD

**Issue by GuoMieClub** [getsurfboard/surfboard#91]
通过订阅链接下载文件后导入可正常使用，但使用url导入同一订阅文件则导入失败，错误代码http：0

**Comment by getsurfboard** [comment]
是在开代理的情况下导入链接的吗？

**Comment by cjhxc** [comment]
> 是在开代理的情况下导入链接的吗？

订阅转换开着代理url导入会http：0

**Comment by GuoMieClub** [comment]
已解决，订阅转换的链接内含失效的链接会导致失败
