### ISSUE TITLE
建议磁贴显示当前的配置名称

### ISSUE THREAD

**Issue by L-Altair** [getsurfboard/surfboard#99]
建议在下拉栏的磁体显示当且的配置名称而不是surfboard,这样有助于快速确认在使用哪个配置而不用进入app以内.
btw,谢谢作者大大的工作

**Comment by getsurfboard** [comment]
配置名称已经显示在磁铁副标题上，如果不显示应该是ROM本身的改动。

这里为了兼容性，会继续维持主标题为“Surfboard”，副标题为配置名称。
